name: numpypandas
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - jupyter
  - jupyterlab
  - jupyter_contrib_nbextensions
  - seaborn
  - altair
  - pip
  - ipywidgets
  - pip:
    - plotnine
    - xlrd
    - ipydatagrid
    - lckr-jupyterlab-variableinspector
    - jupyterlab-spellchecker
    - openpyxl
