name: DAVPy
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - scikit-image
  - statsmodels
  - jupyterlab
  - seaborn
  - ipywidgets
  - pip
  - pip:
    - plotnine
    - plotly
    - xlrd
    - openpyxl
    - lckr-jupyterlab-variableinspector
    - jupyterlab-spellchecker
    - requests
    - microfilm