name: DAVPy
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - scikit-image
  - statsmodels
  - jupyter
  - jupyterlab
  - seaborn
  - altair
  - pip
  - ipywidgets
  - pip:
    - plotnine
    - plotly
    - xlrd
    - ipydatagrid
    - lckr-jupyterlab-variableinspector
    - jupyterlab-spellchecker
    - openpyxl
    - ipympl
    - requests
    - microfilm